# For more information: https://laravel.com/docs/sail
version: '3.7'
services:
    laravel7:
        build:
            context: docker/php-7.4
            dockerfile: Dockerfile
            args:
                WWWUSER: 1000
                WWWGROUP: 1000
        image: realworldio/laravel-sail:7.4
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
        networks:
            - sail
    laravel8:
        build:
            context: docker/php-8.0
            dockerfile: Dockerfile
            args:
                WWWUSER: 1000
                WWWGROUP: 1000
        image: realworldio/laravel-sail:8.0
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmariadb:
        driver: local
