# For more information: https://laravel.com/docs/sail
version: '3.7'
services:
    laravel7:
        build:
            context: docker/php-8.2
            dockerfile: Dockerfile
            # args:
            #     WWWGROUP: '${WWWGROUP}'
            args:
                WWWGROUP: 1000
        image: realworldio/laravel-sail:8.2
        # ports:
        #     - '${APP_PORT:-80}:80'
        # env_file: ./.env_file
        # environment:
        #     WWWUSER: '${WWWUSER}'
        #     LARAVEL_SAIL: 1
        #     XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        #     XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        # volumes:
        #     - '.:/var/www/html'
        networks:
            - sail
    # laravel8:
    #     build:
    #         context: docker/php-8.0
    #         dockerfile: Dockerfile
    #         # args:
    #         #     WWWGROUP: '${WWWGROUP}'
    #         args:
    #             WWWGROUP: 1000
    #     image: realworldio/laravel-sail
    #     # ports:
    #     #     - '${APP_PORT:-80}:80'
    #     # env_file: ./.env_file
    #     # environment:
    #     #     WWWUSER: '${WWWUSER}'
    #     #     LARAVEL_SAIL: 1
    #     #     XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    #     #     XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    #     # volumes:
    #     #     - '.:/var/www/html'
    #     networks:
    #         - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmariadb:
        driver: local
