name: Docker

on:
  schedule:
    - cron: '30 0 * * *'
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]  # Publish semver tags as releases
  pull_request:
    branches: [ master, build ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: realworldio/laravel-sail

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login to Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      # Build and push Docker image for PHP 7.4
      # - name: Build and push Docker image for PHP 7.4
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./docker/php-7.4
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags || '7.4-latest' }}
      #     labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker image for PHP 8.0
      - name: Build and push Docker image for PHP 8.0
        uses: docker/build-push-action@v4
        with:
          context: ./docker/php-8.0
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags || '8.0-latest' }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker image for PHP 8.1
      - name: Build and push Docker image for PHP 8.1
        uses: docker/build-push-action@v4
        with:
          context: ./docker/php-8.1
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags || '8.1-latest' }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker image for PHP 8.2
      - name: Build and push Docker image for PHP 8.2
        uses: docker/build-push-action@v4
        with:
          context: ./docker/php-8.2
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags || '8.2-latest' }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker image for PHP 8.3
      - name: Build and push Docker image for PHP 8.3
        uses: docker/build-push-action@v4
        with:
          context: ./docker/php-8.3
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags || 'latest' }}
          labels: ${{ steps.meta.outputs.labels }}
