name: Docker

on:
  schedule:
    - cron: '30 0 * * *'
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]  # Publish semver tags as releases
  pull_request:
    branches: [ master, build ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: realworldio/laravel-sail

jobs:
  # Job for logging into Docker registry
  login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      registry_logged_in: ${{ steps.docker_login.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        id: docker_login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  # Job for building PHP 8.0 image
  build-php-8.0:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push Docker image for PHP 8.0
        uses: docker/build-push-action@v4
        # continue-on-error: true
        with:
          context: ./docker/php-8.0
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags || '8.0' }}
            latest
          labels: ${{ steps.meta.outputs.labels }}

  # Job for building PHP 8.1 image
  build-php-8.1:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push Docker image for PHP 8.1
        uses: docker/build-push-action@v4
        # continue-on-error: true
        with:
          context: ./docker/php-8.1
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags || '8.1' }}
          labels: ${{ steps.meta.outputs.labels }}

  # Job for building PHP 8.2 image
  build-php-8.2:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push Docker image for PHP 8.2
        uses: docker/build-push-action@v4
        # continue-on-error: true
        with:
          context: ./docker/php-8.2
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags || '8.2' }}
          labels: ${{ steps.meta.outputs.labels }}

  # Job for building PHP 8.3 image
  build-php-8.3:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push Docker image for PHP 8.3
        uses: docker/build-push-action@v4
        # continue-on-error: true
        with:
          context: ./docker/php-8.3
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags || '8.3' }}
          labels: ${{ steps.meta.outputs.labels }}
